version: '3.1'

services:

    postgres:
        container_name: postgres
        image: postgres:11-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_MULTIPLE_DATABASES=${SHARED_POSTGRES_DB_NAMES}
            - POSTGRES_PASSWORD=${SHARED_POSTGRES_PASSWORD}
            - POSTGRES_USER=${SHARED_POSTGRES_USER}
            # - POSTGRES_DB=${SHARED_POSTGRES_DB}
            #- DB_ANON_ROLE=${SHARED_DB_ANON_ROLE}
        volumes:
            - pgdata:/var/lib/postgresql/data
            # anything in initdb directory is created in the database
            # see "How to extend this image" section at https://hub.docker.com/r/_/postgres/
            - "./local-stack/postgres/initdb:/docker-entrypoint-initdb.d"
        networks:
            - ppnet
        restart: always

    pgadmin4:
        container_name: pgadmin4-db
        image: dpage/pgadmin4
        environment:
            - TZ=Africa/Johannesburg
            - PGADMIN_DEFAULT_EMAIL=${PG4_ADMIN_USER}
            - PGADMIN_DEFAULT_PASSWORD=${PG4_ADMIN_PASSWORD}
        volumes:
            - "./local-stack/postgres/config/pgadmin4-servers.json:/pgadmin4/servers.json"
            #   - ${PWD}/pgadmin4_mnt:/var/lib/pgadmin
            # add the above line to mount the container to local storage if you need to export/import data.
        ports:
            - 8081:80
        networks:
            - ppnet

volumes:
    pgdata: